apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: review-service
  name: review-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: review-service
  template:
    metadata:
      labels:
        app: review-service
    spec:
      containers:
        - image: rbiedrawa/review-service:0.0.1-SNAPSHOT
          name: review-service
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 300
            timeoutSeconds: 20
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
          envFrom:
            - configMapRef:
                name: review-service