apiVersion: v1
kind: Service
metadata:
  labels:
    app: customer-service
  name: customer-service
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: customer-service
  type: ClusterIP